module.exports = {
	"logo": require('./logo.png'),
	"splash": require('./splash.png'),
	"menu": require('./hamburger.png'),
	"info": require('./info.png'),
	"back": require('./ic_action_previous_item.png'),

	"refresh": require('./ic_action_refresh.png'),
	"prevButton":	require('./ic_action_previous_item.png'),
	"nextButton": require('./ic_action_next_item.png'),
	"checked": require('./checked_checkbox.png'),
	"unchecked": require('./unchecked_checkbox.png'),

	"axis": require('./axis.png'),
	"axis-east": require('./axis-east.png'),
	"axis-south": require('./axis-south.png'),
	"allies": require('./allies.png'),
	"allies-south": require('./allies-south.png'),
	"allies-east": require('./allies-east.png'),
	"allies-west": require('./allies-west.png'),
	"german": require('./germany.png'),
	"soviet": require('./ussr.png'),
	"japanese": require('./japan.png'),
	"communist": require('./communist.png'),
	"un": require('./un.jpg'),
	"vichy": require('./france.png'),

	"tie": require('./tie.png'),
	"burma": require('./burma.jpg'),
	"dak": require('./dak.jpg'),
	"enemyatthegates": require('./enemyatthegates.jpg'),
	"guderiansblitzkrieg": require('./guderiansblitzkrieg.jpg'),
	"hubespocket": require('./hubespocket.jpg'),
	"korea": require('./korea.jpg'),
	"reluctantenemies": require('./reluctantenemies.jpg'),
	"sicily": require('./sicily.jpg'),
	"theblitzkrieglegend": require('./theblitzkrieglegend.jpg'),
	"tunisia": require('./tunisia.jpg')
};
