import { Icons } from 'react-native-nub';

module.exports = {
	"logo": require('./logo10.png'),
	"splash": require('./splash.png'),
	"menu": Icons['menu-dark'],
	"info": Icons['info-dark'],
	"refresh": Icons['refresh-dark'],
	"back": Icons['chevron-left-dark'],
	"eraser": require('./reset-2.png'),

	"axis": require('./axis.png'),
	"axis-east": require('./axis-east.png'),
	"axis-south": require('./axis-south.png'),
	"allies": require('./allies.png'),
	"allies-south": require('./allies-south.png'),
	"allies-east": require('./allies-east.png'),
	"allies-west": require('./allies-west.png'),
	"german": require('./germany.png'),
	"soviet": require('./ussr.png'),
	"japanese": require('./japan.png'),
	"communist": require('./communist.png'),
	"un": require('./un.png'),
	"vichy": require('./france.png'),

	"tie": require('./tie.png'),
	"burma": require('./burma.jpg'),
	"dak": require('./dak.jpg'),
	"enemyatthegates": require('./enemyatthegates.jpg'),
	"guderiansblitzkrieg": require('./guderiansblitzkrieg.jpg'),
	"hubespocket": require('./hubespocket.jpg'),
	"korea": require('./korea.jpg'),
	"reluctantenemies": require('./reluctantenemies.jpg'),
	"sicily": require('./sicily.jpg'),
	"theblitzkrieglegend": require('./theblitzkrieglegend.jpg'),
	"tunisia": require('./tunisia.jpg'),
	"smolensk": require('./smolensk.png'),
	"btr": require('./btr.jpg'),
	"bg": require('./bg.jpg')
};
